### ISSUE TITLE
TypeBuilder.hx - Uncaught exception Null Access

### ISSUE THREAD

**Issue by Zavim** [deepnight/ldtk-haxe-api#23]
I've tried to figure this out myself for a few hours but I'm very new to Haxe.
```
/home/USER/haxelib/ldtk-haxe-api/git/src/ldtk/macro/TypeBuilder.hx:938: lines 938-944 : Uncaught exception Null Access
/home/USER/haxelib/ldtk-haxe-api/git/src/ldtk/macro/TypeBuilder.hx:82: characters 3-21 : Called from here
/home/USER/haxelib/ldtk-haxe-api/git/src/ldtk/Project.hx:36: characters 11-61 : Called from here
src/game/assets/World.hx:4: characters 5-80 : Called from here
```
This error occurs when I try to compile for any of the 4 platform options after following the guide on your site. I'm on Pop!_OS 22.04 LTS which is based on Ubuntu 22.04 LTS.

Haxe 4.2.5
ase: [2.0.1]
castle: [git]
deepnightLibs: 1.0.73 [git]
format: [3.5.0]
heaps-aseprite: 0.1.2 [git]
heaps: [git]
hldx: [1.10.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]
hscript: 2.5.0 [git]
ldtk-haxe-api: 1.0.0 [git]
redistHelper: [0.7.3]

**Comment by deepnight** [comment]
Hi! Thanks for reporting this bug and sorry for inconvenience.

It's fixed, you may update the lib: 

```
haxelib update ldtk-haxe-api
```
