### ISSUE TITLE
1.3.2-rc.1 doesn't work without multi-world enabled

### ISSUE THREAD

**Issue by zommerfelds** [deepnight/ldtk-haxe-api#28]
EDIT: please see new message below

Despite multiple worlds being "experimental" (and optional!) in the editor, the library gives me deprecation warnings like:

```
Warning : DEPRECATED! Use "myProject.all_worlds.Default.levels"
```

But when I use the suggested code, I get a runtime exception:

```
[Ldtk-api] Couldn't instanciate World class LdtkProject_World_undefined
```

I don't need multi-world right now, so not sure if I want to switch just because of this warning.

What do you think is the best solution?
1) Don't show warning (since the feature is still optional)
2) Populate the default world even if multi-world is disabled in the editor
3) Something else?

NOTE: my target is JS

**Comment by zommerfelds** [comment]
Happy to help with a PR if you'd like (seems simple  enough).

**Comment by zommerfelds** [comment]
Actually sorry, I realized it's not just about the warning. I get the above exception no matter if I use the deprecated code or the new Default field. I can only fix it by enabling multi-world in the editor. Maybe there is something wrong with the default world.

**Comment by zommerfelds** [comment]
This fixed it for me: https://github.com/deepnight/ldtk-haxe-api/issues/28

**Comment by deepnight** [comment]
Amazing, thanks for the report & fix :)
