### ISSUE TITLE
How to Render Maps in Canvas

### ISSUE THREAD

**Issue by harshetmaruff** [deepnight/ldtk-haxe-api#5]
Hi everyone, I have a question, how do i render the map in the canvas ??

**Comment by deepnight** [comment]
Hi,
You should check the `samples` directory in the ldtk-haxe-api folder, which contains some usage examples:

https://github.com/deepnight/ldtk-haxe-api/tree/master/samples

**Comment by harshetmaruff** [comment]
How do i add collision to a particular layer

**Comment by NaxeCode** [comment]
> How do i add collision to a particular layer

@harshetmaruff Are you using HaxeFlixel or Heaps as a base?

**Comment by harshetmaruff** [comment]
@NaxeCode Heaps deepnight gameBase
